### ISSUE TITLE
Failed to fetch schema. Please check your connection

### ISSUE THREAD

**Issue by koin-master** [DimiMikadze/orca#104]
**Describe the bug**

can you please help me to solve this problem

Thank's

![rapport](https://user-images.githubusercontent.com/51753191/105021339-b96cea00-5a48-11eb-86bf-eaab33dd75ee.JPG)

**Comment by Arif1951995** [comment]
in /utils/apollo-server change checkAuthorization to this :
const checkAuthorization = (token) => {
  return new Promise(async (resolve, reject) => {
    try {
      const authUser = await jwt.verify(token, process.env.SECRET);
      return authUser;
    } catch (error) {
      return '';
    }
  });
};

**Comment by xadhrit** [comment]
just put a if statement like this : `
    if (token == null){
      console.error('Token is Null , Please Sign Up!');
      return;
    }
`

**Comment by DimiMikadze** [comment]
Hi, I'm closing this issue since we uploaded a new project to this repository. The old one is located here: https://github.com/DimiMikadze/create-social-network-old.
