### ISSUE TITLE
Logging out does not unsubscribe subscriptions

### ISSUE THREAD

**Issue by SnekNOTSnake** [DimiMikadze/orca#111]
![ss](https://user-images.githubusercontent.com/46426464/114057958-3deb3e00-98bd-11eb-8cf0-9f7c35c8d2ce.png)

**Describe the bug**

The title pretty much sums it up.

**System**

Browser version: Google Chrome Version 89.0.4389.72 (Official Build) (64-bit)
Node.js version: NVM v14.15.4
NPM or Yarn version: Yarn 1.22.5
Operating system: Linux Mint 19.3 Tricia

**Steps to reproduce**

1. Browser 1: Log into some random account
2. Browser 1: Log out
3. Browser 2: Log into another account
4. Browser 2: Make some interaction with Browser 1's logged out account (e.g. Follow)
5. Browser 1: Expect messages in the still open Subscription

**Expected behavior**

After logging out, the user should no longer receive any notifications and the Subscription should be closed.

**Actual behavior**

After logging in, the user still receives notification packages and the Subscription is still open.

**Reproducible demo**

Empty.

**Additional context**

The problem (I think) is mainly located in the [`onConnect()`](https://github.com/DimiMikadze/create-social-network/blob/117316406af8e34356584a23b95f13a4ce51e797/api/utils/apollo-server.js#L54-L72) subscription function, where it's only being called **once** at the very first handshake. Also, the [`unsubscribe()`](https://github.com/DimiMikadze/create-social-network/blob/117316406af8e34356584a23b95f13a4ce51e797/frontend/src/components/App/App.js#L67) function in the `App.js` seems not being called when the user logs out; otherwise the Subscription would have been closed.

The simplest solution IMO would be to just reload the page when user log out. But it would sacrifice user experience a bit. Is there another solution for this?

**Comment by DimiMikadze** [comment]
Hi, I'm closing this issue since we uploaded a new project to this repository. The old one is located here: https://github.com/DimiMikadze/create-social-network-old.
