### ISSUE TITLE
MongooseServerSelectionError: connection timed out

### ISSUE THREAD

**Issue by Arif1951995** [DimiMikadze/orca#120]
the front-end is running but  the server giving this error  "MongooseServerSelectionError: connection timed out"

![Capture](https://user-images.githubusercontent.com/40889693/123511326-0c9f3480-d69a-11eb-82f0-55ad853714ed.PNG)

**Comment by bemolxd** [comment]
I suggest creating your own MongoDB Atlas cluster. The example one may be already shut down.

**Comment by DimiMikadze** [comment]
Hi, I'm closing this issue since we uploaded a new project to this repository. The old one is located here: https://github.com/DimiMikadze/create-social-network-old.
