### ISSUE TITLE
netlify.toml

### ISSUE THREAD

**Issue by liester** [DimiMikadze/orca#13]
**Describe the bug**

Using `yarn create social-network my-network`  creates a netlify.toml with a `publish = "frontend/build"`.  Following the frontend deployment guide to netlify results in the netlify.toml overriding the build settings, which is desired.  Unfortunately, it leads to this netlify error.
`failed during stage 'building site': Deploy directory 'frontend/frontend/build' does not exist`
Updating the netlify.toml to have a `base = "frontend"` and `publish="build"`` resolves the issue on netlify.

**System**

Node.js version: 11.11.0
NPM or Yarn version: Yarn 1.15.2
Operating system: Windows 10

**Steps to reproduce**
(Write your steps here:)

1. yarn create social-network my-network
2. push the entire repo to github
3. link github repo to netlify
4. deploy master branch of github repo via netlify

**Expected behavior**

React frontend is available after netlify deploy steps completed.

**Actual behavior**

Netlify fails to deploy the react application based on the netlify.toml
![image](https://user-images.githubusercontent.com/6137420/66258034-08b0dd80-e766-11e9-9fec-e8f451022c81.png)

**Reproducible demo**

https://github.com/liester/test-social-network

**Additional context**

I have created a PR for the netlify.toml modification.

**Comment by DimiMikadze** [comment]
Hi @liester thanks for reporting the issue and PR for fixing it! 👍
