### ISSUE TITLE
Register not work

### ISSUE THREAD

**Issue by Butonix** [DimiMikadze/orca#130]
POST https://api.getorca.org/signup 500 (Internal Server Error)
Oops! Something went wrong. Please send an error report to help us improve your experience.

**Comment by DimiMikadze** [comment]
@Butonix Hi, thanks for reporting an issue so quickly  😛. After open-sourcing the project Mailgun decided to disable our account due to `exposed account credentials`. This is not the case but anyway we are waiting for their support to enable it.
