### ISSUE TITLE
A Post should not be clickable on its page.

### ISSUE THREAD

**Issue by DimiMikadze** [DimiMikadze/orca#136]
When you click on a post in a list, it redirects you to the specific post page. This is good, because there's more space to interact with the post, and it contains post specific URL to share with others. However, it should not be clickable anymore because it redirects to the same page.

**Comment by RajendrasinhParmar** [comment]
@DimiMikadze I've worked on the feature and tested the changes locally. there are working fine.
However, this is my first contribution to this repository so can you please let me know in case there is anything about the PR and code that might be missing from my end?

**Comment by DimiMikadze** [comment]
@RajendrasinhParmar thank you for working on this. Your PR looks excellent!
