### ISSUE TITLE
Inner scroll for search result container

### ISSUE THREAD

**Issue by DimiMikadze** [DimiMikadze/orca#157]
We need to add a scroll to the container that displays search results. Otherwise, when the result list is too long, users can't see the bottom items of the list.

<img width="552" alt="Screen Shot 2021-10-13 at 10 07 20 PM" src="https://user-images.githubusercontent.com/8871615/137189039-8c6ce5be-4b60-4d36-85c9-e5a0add23f76.png">

**Comment by itsmais** [comment]
Hello! 👋 Could you please check my [pull request](https://github.com/ElevenSymbols/orca/pull/160)?
