### ISSUE TITLE
Text cropping in the PostCard component on different resolutions.

### ISSUE THREAD

**Issue by DimiMikadze** [DimiMikadze/orca#176]
On some screen resolutions, the text gets appropriately cropped in the PostCard component, but on other screen resolutions, the last line of the text is halfway visible.

If it can be fixed by tweaking the "TITLE_INITIAL_HEIGHT" value that's good. Otherwise, we need to come up with a different solution.

Screenshot of the bug:

<img width="524" alt="Screen Shot 2021-10-22 at 9 26 29 AM" src="https://user-images.githubusercontent.com/8871615/138397943-e8723f18-8f38-4025-bbf6-fda6e207edb0.png">

**Comment by RajendrasinhParmar** [comment]
@DimiMikadze I've worked on the see more functionality-related fix. Can you please take a look into PR and check if this is the proper fix or not?
