### ISSUE TITLE
Laas setup

### ISSUE THREAD

**Issue by alearnauser** [DimiMikadze/orca#180]
Hello, i has bought a vps under debian 11 on mvps.net 
I has try to setup it, it works but i dont know what link i need to enter in .env of orca-api...
I has point it to the ip of the vps but it's not works...
I dont know what i has to do, please describe me the setup of it on vps 
And i use node 12.22, yarn and git.
Or for explain me, add me on discord : 
doom_the_thomas#1378

Thanks if you help me !

**Comment by DimiMikadze** [comment]
Hi @alearnauser, everything is documented in the Orca docs, in the deployment section: https://getorca.org/docs/deployment/deployment

We can't help with individual deployments, sorry.
