### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by ImKyleJK** [DimiMikadze/orca#189]
### What version of Node.js are you using?

16.13.1

### What version of Yarn are you using?

1.22.17

### What browser are you using?

OperaGX

### What operating system are you using?

Windows

### Describe the Bug

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'data')

Source
.next\static\chunks\pages\_app.js (60:37) @ _callee2$

   58 |       dispatch(closeAuthPopup());
   59 |     } catch (error) {
> 60 |       setErrorMessage(error.response.data);
        |                                     ^
  61 |     }
  62 |   };
  63 | 
  
Call Stack

Generator.invoke [as _invoke]
.next\static\chunks\main.js (294:0)

asyncGeneratorStep
.next\static\chunks\pages\_app.js (3:0)

### Expected Behavior

When i try to login it shows this.

### Steps to reproduce

Run yarn create-orca-app test
cd test
yarn dev
Create admin account
Sign in

**Comment by DimiMikadze** [comment]
@CheckyMC this error tells you that `data` is not defined in `error.response`. Just console log `error` and see why you are not able to log in. It can be many things, maybe your MongoDB connection is not successful,  or you are not able to create an admin user.

**Comment by ImKyleJK** [comment]
Never thought of that, I will log it when I get back on my computer.

**Comment by ImKyleJK** [comment]
Where is this file where I need to log the error?

**Comment by DimiMikadze** [comment]
@CheckyMC There is no file. `console.log` logs error into the Browser console.
