### ISSUE TITLE
Config CORS vercel/GCP

### ISSUE THREAD

**Issue by sebaestel** [DimiMikadze/orca#200]
### What version of Node.js are you using?

v16.1.0

### What version of Yarn are you using?

1.22.18

### What browser are you using?

Chrome

### What operating system are you using?

macOS Monterrey 

### Describe the Bug

I deploy an Orca Front end  in vercel and the API in GCP
FE: https://buzzi-ogfwwk1bl-sebaestel.vercel.app/
API: https://fotosub-api-350712.rj.r.appspot.com/
My cors configs in GCP are:
```
[
    {
      "origin": [
        "https://localhost:3000",
        "https://buzzi-ogfwwk1bl-sebaestel.vercel.app",
        "https://buzzi-topaz.vercel.app",
        "*"
      ],
      "responseHeader": "*",
      "method": ["GET", "PUT", "POST", "OPTIONS", "HEAD"],
      "maxAgeSeconds": 3600
    }
]
```

But is not working, the error is:
`Access to XMLHttpRequest at 'https://fotosub-api-350712.rj.r.appspot.com/channels' from origin 'https://buzzi-ogfwwk1bl-sebaestel.vercel.app' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'http://localhost:3000' that is not equal to the supplied origin`

Can anyone helpme with this?

### Expected Behavior

.

### Steps to reproduce

.

**Comment by DimiMikadze** [comment]
Hi @sebaestel, most likely, you are not setting the environment variables correctly, or the CORS config is not correct in the GCP.

For the environment variables, you can read more in the deployment section: https://dimimikadze.github.io/orca-docs/docs/deployment/deployment

**Comment by sebaestel** [comment]
thanks! is fixed!
