### ISSUE TITLE
Follow/Unfollowing users with posts can cause TypeError: _data$getUserPosts is undefined

### ISSUE THREAD

**Issue by ganonbit** [DimiMikadze/orca#31]
**Describe the bug**

When going to new, non followed users profiles and following/unfollowing them in a row it can cause a `TypeError: _data$getUserPosts is undefined` error. 

**System**

Node.js version: v12.12.0
NPM or Yarn version: yarn 1.19.1
Operating system: MAC OS

**Steps to reproduce**

1. go to new users profile
2. follow
3. unfollow
4. repeat until error

**Expected behavior**

would follow and unfollow, or x out clicking of button like when spamming the like button off and on current does.

**Actual behavior**

sometimes after just unfollowing after following, sometimes after about 4 times, it will bring this error. 

<img width="1066" alt="Screen Shot 2019-11-08 at 4 08 13 PM" src="https://user-images.githubusercontent.com/4486563/68514268-d56cdd00-0242-11ea-94cb-bed8371beb78.png">

```TypeError: _data$getUserPosts is undefined
ProfilePosts/<
src/pages/Profile/ProfilePosts.js:51

  48 |   variables={variables}
  49 |   notifyOnNetworkStatusChange
  50 | >
> 51 |   {({ data, loading, fetchMore, networkStatus }) => {
     | ^  52 |     if (loading && networkStatus === 1) {
  53 |       return (
  54 |         <Skeleton```



**Reproducible demo**

localhost

**Additional context**

trying to stress test site functionality for issues with heavy interaction.

**Comment by ganonbit** [comment]
similar bugs like this I faced were due to queries, so I'm going to take a look there first

**Comment by ganonbit** [comment]
Looks like its only on localhost 🙄 , so it might be just a me thing. I'll double check.

**Comment by DimiMikadze** [comment]
Hi @reesecode I tried to reproduce this bug on my end on localhost but without any luck, maybe you have some changes that is causing it?

**Comment by DimiMikadze** [comment]
@reesecode I'm going to close this issue, since I can't replicate it, but feel free to reopen it 👍
