### ISSUE TITLE
Start message from scratch with user.

### ISSUE THREAD

**Issue by TomKochievi** [DimiMikadze/orca#32]
**Describe the bug**
When start messaging with user sometimes gives error.
It happens only on localhost.

**System**

Node.js version: v12.3.1
NPM or Yarn version: Yarn 1.16.0
Operating system: Windows OS

**Steps to reproduce**
(Write your steps here:)

1. Go to user profile.
2. Click `Message` button.
3. Write new message and send.
4. Reload message page.

**Expected behavior**

(Write what you thought would happen.)

**Actual behavior**

![message-bug](https://user-images.githubusercontent.com/13495707/68583467-a189f580-0496-11ea-8c2a-75e802beb51c.jpg)

**Reproducible demo**

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Additional context**

**Comment by DimiMikadze** [comment]
@TomKochievi can't replicate it on my end maybe you have some changes that is causing it? Closing it right now, but feel free to reopen it or if you'll find the fix please send the PR
