### ISSUE TITLE
can not copy the post link from the post

### ISSUE THREAD

**Issue by morganwang010** [DimiMikadze/orca#33]
**Describe the bug**
from the post, click the copy link, then apperas the error
(Write your answer here.)

**System**
 
Node.js version: 12.13.0
NPM or Yarn version:6.12.0
Operating system: centos7.6

**Steps to reproduce**
(Write your steps here:)

1.add a post，then share, finish the add process.
2.at the top-right of the new post ,click the ...　button，then pop up a window
3. click the copy link, then the error appears

**Expected behavior**
get the link in the clipboard
(Write what you thought would happen.)

**Actual behavior**

(Write what happened. Please add screenshots!)
×
TypeError: Cannot read property 'writeText' of undefined
copyToClipboard
src/components/PostCard/PostCardOption.js:50
  47 | const [{ auth }] = useStore();
  48 | 
  49 | const copyToClipboard = () => {
> 50 |   navigator.clipboard.writeText(
     | ^  51 |     `${process.env.REACT_APP_FRONTEND_URL}${generatePath(Routes.POST, {
  52 |       id: postId,
  53 |     })}`

**Reproducible demo**

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Additional context**

**Comment by DimiMikadze** [comment]
Hi @morganwang010 I can't replicate this on my end, I think it has to be Browser issue, can you tell me which web Browser are you using?

Also when you follow above mentioned steps only after that this error happens or also when you just try to copy to clipboard other posts?

**Comment by morganwang010** [comment]
hi @DimiMikadze ,  I send a email to your mailbox dimi@udilia.com about the website I set. You can visit the website and inspect the question. Thank you very much.

**Comment by DimiMikadze** [comment]
@morganwang010 try to reproduce that error on https://worldexplorer.netlify.com/ this is our demo website. I haven't received your email but we should understand if this error exists on master branch.
