### ISSUE TITLE
create groups

### ISSUE THREAD

**Issue by mohamed0group** [DimiMikadze/orca#34]
i like this project and encourage you to move foreword, but it will be a good idea if the user can create group and the group have admin ,moderator and editor to share private posts, admin and moderator can accept or decline request of the follower to follow the group, and admin can create or delete moderator role in the group.

**Comment by DimiMikadze** [comment]
Hi, thanks for your feedback. We are not planning to create admin panel for this project, as we are planning to create mobile app for it, but if you want to work on this issue, i'll be happy to merge your PR 👍
