### ISSUE TITLE
Add Image navigation

### ISSUE THREAD

**Issue by cloudorbush** [DimiMikadze/orca#35]
Would be nice if you could click the right (or left) side of the picture and it would take you to the previous (or next) picture. 

Even better, if you could use the arrow keys on the keyboard for it.

![SharedScreenshot](https://user-images.githubusercontent.com/57633368/70111509-b0f1fe00-1652-11ea-82b7-cfb42a3713c0.jpg)

**Comment by DimiMikadze** [comment]
Hi, we are not planning implement it, but if you want to work on this issue, feel free to send a PR. as for UI and functionality it should work exactly as it's done on Instagram.
