### ISSUE TITLE
Turn this project into a course

### ISSUE THREAD

**Issue by armaandh** [DimiMikadze/orca#37]
Hi Dimi. I really like this project and I think it is very educational. Would you consider making this into a course on Udemy, similar to your:

https://www.udemy.com/course/learn-react-by-building-and-deploying-production-ready-app/

I would definitely love to have a step by step on how you made this and would pay for a nice tutorial series!

**Comment by DimiMikadze** [comment]
Hello @armaandh , thank you! Unfortunately no, because it takes a lot of time and energy to produce video course and outcome is near to zero :) thanks!
