### ISSUE TITLE
The demo is down?

### ISSUE THREAD

**Issue by fabiooshiro** [DimiMikadze/orca#38]
**Describe the bug**

![Screenshot from 2020-02-02 10-13-20](https://user-images.githubusercontent.com/218768/73608682-be6d2b00-45a4-11ea-8d7c-e7e257983bc8.png)

**System**

Browser version: Chromium Version 79.0.3945.79 (Official Build) Built on Ubuntu
Operating system: running on Ubuntu 18.04 (64-bit)

**Additional context**

I have an account previously created

**Comment by DimiMikadze** [comment]
Hi, Demo database is being deleted and populated with demo data daily, hence you need to create new user if you want to access demo website. 

If you are developing locally i recommend you to create your own mLab and Cloudinary user: https://github.com/dimimikadze/create-social-network#requirements-and-configuration

**Comment by kafiln** [comment]
@fabiooshiro just delete your localstorage and everything will be back to normal.
