### ISSUE TITLE
TypeError: Cannot read property 'getAuthUser' of undefined

### ISSUE THREAD

**Issue by bauersfeld** [DimiMikadze/orca#39]
**Describe the bug**

I get this error when trying to connect to my local instance of mongo db.

TypeError: Cannot read property 'getAuthUser' of undefined

**Comment by DimiMikadze** [comment]
@bauersfeld Hi, maybe that happens because you have not logout before switching database, try to clear localStorage and refresh the browser.

If that won't help, make sure that server is successfully connecting to database.

**Comment by bauersfeld** [comment]
Hi Dimi-  

That worked, but now when I try to upload a profile photo I get an exception and the problem comes back.  Here is the exception:

```
Unhandled Rejection (TypeError): Cannot read property 'message' of undefined
_callee$
src/pages/Profile/ProfileImageUpload.js:108
  105 | } catch (err) {
  106 |   console.log(err);
  107 | 
> 108 |   message.error(err.graphQLErrors[0].message);
      | ^  109 | }
  110 | 
  111 | setLoading(false);
```

I'm very interested in your project and would be happy to help.  Have you made any additional changes or fixes that you could push the git?

**Comment by DimiMikadze** [comment]
@bauersfeld please read `err` variable, it should contain information regarding your problem. I'm guessing your app is having a problem while trying to connect to Cloudinary CDN.

Even though I'm not planning to add additional features to the app in the near future, contribution is more than welcome, just please read [CONTRIBUTING.md](https://github.com/dimimikadze/create-social-network/blob/master/CONTRIBUTING.md)  before submitting a Pull Request to the project.
