### ISSUE TITLE
I need help with replace ws error

### ISSUE THREAD

**Issue by cichy** [DimiMikadze/orca#40]
**Describe the bug**
getting error 
<img width="471" alt="Screenshot 2020-03-19 at 13 18 10" src="https://user-images.githubusercontent.com/443253/77067552-66b84100-69e5-11ea-9565-9c74e3e29111.png">
on production site 
(Write your answer here.)

**System**

Browser version:
Node.js version:
NPM or Yarn version:
Operating system:

**Steps to reproduce**
(Write your steps here:)

1.
2.
3.

**Expected behavior**

(Write what you thought would happen.)

**Actual behavior**

(Write what happened. Please add screenshots!)

**Reproducible demo**

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Additional context**

**Comment by DimiMikadze** [comment]
you don't have `API_URL` defined, IDE is showing you an error with its description.

**Comment by cichy** [comment]
# API URL
REACT_APP_API_URL=FRONTEND_URL=http://mysite.herokuapp.com

# WebSocket URL, if not specified app will use API_URLs value by replacing http(s) to ws 
REACT_APP_WEBSOCKET_API_URL=ws://mysite.herokuapp.com

# Front end URL
REACT_APP_FRONTEND_URL=https://mysite.com

**Comment by cichy** [comment]
how to define this correctly on heroku for graphql?
REACT_APP_API_URL=FRONTEND_URL=http://myapp.herokuapp.com
REACT_APP_WEBSOCKET_API_URL=ws://lmyapp.herokuapp.com
REACT_APP_FRONTEND_URL=https://mypage.com
