### ISSUE TITLE
How to API define env ?

### ISSUE THREAD

**Issue by cichy** [DimiMikadze/orca#41]
**Describe the topic**
how to define these ecorrectly on heroku for graphql?
REACT_APP_API_URL=FRONTEND_URL=https://myapp.herokuapp.com
REACT_APP_WEBSOCKET_API_URL=ws://myapp.herokuapp.com
REACT_APP_FRONTEND_URL=https://mypage.com

**Comment by DimiMikadze** [comment]
@cichy You can use Google for this kind of questions, please stop opening/closing new issues every 2 min.

https://devcenter.heroku.com/articles/config-vars
