### ISSUE TITLE
Facing error while deploying the app on heroku

### ISSUE THREAD

**Issue by anishagg17** [DimiMikadze/orca#45]
**Describe the topic**

![Screenshot 2020-03-26 at 12 54 20 AM](https://user-images.githubusercontent.com/43617894/77577180-55e36000-6efc-11ea-9de5-6a06221488d0.png)

heroku logs this error even when I whitelist all the API from MongoDB atlas

**Comment by DimiMikadze** [comment]
@anishagg17 Hi, I can't help you with the integration of third party services, you need to further investigate that error, it could be an issue while app is trying to connect to remote database.

**Comment by cichy** [comment]
Try to add TopologyDescription and set it to true in mongoose connect object.
