### ISSUE TITLE
How to make project support video in create a post

### ISSUE THREAD

**Issue by mazenElmarsfawy** [DimiMikadze/orca#49]
Hi, Dimi could you tell me the steps to follow to make the project support upload video in a post?

**Comment by DimiMikadze** [comment]
Hi, you need to become familiar with Cloudinary API: https://cloudinary.com/documentation/upload_videos

You can check how Image uploading is implemented, currently on server and client.
**server**: https://github.com/DimiMikadze/create-social-network/blob/master/api/utils/cloudinary.js
**client**: https://github.com/DimiMikadze/create-social-network/blob/master/frontend/src/pages/Home/PostImageUpload.js

**Comment by mazenElmarsfawy** [comment]
Thanks a lot
