### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by NickNck** [DimiMikadze/orca#55]
Hi i get this error TypeError: Cannot read property 'replace' of undefined in this bit of code :

  17 | // GraphQL WebSocket (subscriptions) URL.
  18 | // If its url is not set in .env then it has same url, host and pathname
  19 | const WEBSOCKET_API_URL = process.env.REACT_APP_WEBSOCKET_API_URL;
> 20 | const websocketApiUrl = WEBSOCKET_API_URL
  21 |   ? WEBSOCKET_API_URL
  22 |   : API_URL.replace('https://', 'ws://').replace('http://', 'ws://');

located under the directory frontend/src/index.js

**Comment by DimiMikadze** [comment]
Hi, I think that happens because, the app isn't able to find environment variables. e.g. `REACT_APP_WEBSOCKET_API_URL`

**Comment by NickNck** [comment]
HI thanks for the quick reply. May i ask why does this happen? For some reason i also got a string error with the env variable for mongodb link so i had to manually enter the string within mongo.connect() and it worked...so im assuming i have to do something similar for websocket api url?

**Comment by NickNck** [comment]
So how can i solve this please? Very new to javascript and react

**Comment by DimiMikadze** [comment]
You need to learn what environment variables are and how to use them in Node.js ecosystem. After learning it, read repositories readme carefully and you'll be able to solve this issue.

**Comment by NickNck** [comment]
The program compiles successfully but now i get this error:

×
TypeError: Cannot read property 'getAuthUser' of undefined
App
C:/Users/yanic/Downloads/create-social-network-master/create-social-network-master/frontend/src/components/App/App.js:119
  116 | <GlobalStyle />
  117 | 
  118 | <ScrollToTop>
> 119 |   <Switch>
      | ^  120 |     {data.getAuthUser ? (
  121 |       <Route
  122 |         exact
View compiled
▼ 17 stack frames were expanded.
renderWithHooks
C:/Users/yanic/Downloads/create-social-network-master/create-social-network-master/node_modules/react-dom/cjs/react-dom.development.js:14803
updateFunctionComponent
C:/Users/yanic/Downloads/create-social-network-master/create-social-network-master/node_modules/react-dom/cjs/react-dom.development.js:17034
beginWork
C:/Users/yanic/Downloads/create-social-network-master/create-social-network-master/node_modules/react-dom/cjs/react-dom.development.js:18610
HTMLUnknownElement.callCallback
C:/Users/yanic/Downloads/create-social-network-master/create-social-network-master/node_modules/react-dom/cjs/react-dom.development.js:188
invokeGuardedCallbackDev
C:/Users/yanic/Downloads/create-social-network-master/create-social-network-master/node_modules/react-dom/cjs/react-dom.development.js:237
invokeGuardedCallback
C:/Users/yanic/Downloads/create-social-network-master/create-social-network-master/node_modules/react-dom/cjs/react-dom.development.js:292
beginWork$1
C:/Users/yanic/Downloads/create-social-network-master/create-social-network-master/node_modules/react-dom/cjs/react-dom.development.js:23203
performUnitOfWork
C:/Users/yanic/Downloads/create-social-network-master/create-social-network-master/node_modules/react-dom/cjs/react-dom.development.js:22157
workLoopSync
C:/Users/yanic/Downloads/create-social-network-master/create-social-network-master/node_modules/react-dom/cjs/react-dom.development.js:22130
performSyncWorkOnRoot
C:/Users/yanic/Downloads/create-social-network-master/create-social-network-master/node_modules/react-dom/cjs/react-dom.development.js:21756
(anonymous function)
C:/Users/yanic/Downloads/create-social-network-master/create-social-network-master/node_modules/react-dom/cjs/react-dom.development.js:11089
unstable_runWithPriority
C:/Users/yanic/Downloads/create-social-network-master/create-social-network-master/node_modules/scheduler/cjs/scheduler.development.js:653
runWithPriority$1
C:/Users/yanic/Downloads/create-social-network-master/create-social-network-master/node_modules/react-dom/cjs/react-dom.development.js:11039
flushSyncCallbackQueueImpl
C:/Users/yanic/Downloads/create-social-network-master/create-social-network-master/node_modules/react-dom/cjs/react-dom.development.js:11084
flushSyncCallbackQueue
C:/Users/yanic/Downloads/create-social-network-master/create-social-network-master/node_modules/react-dom/cjs/react-dom.development.js:11072
scheduleUpdateOnFiber
C:/Users/yanic/Downloads/create-social-network-master/create-social-network-master/node_modules/react-dom/cjs/react-dom.development.js:21199
dispatchAction
C:/Users/yanic/Downloads/create-social-network-master/create-social-network-master/node_modules/react-dom/cjs/react-dom.development.js:15660
▲ 17 stack frames were expanded.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

**Comment by NickNck** [comment]
In console of chrome developer tools it outputs this:

WebSocket connection to 'ws://localhost:4000/graphql' failed: WebSocket is closed before the connection is established.
SubscriptionClient.close @ client.ts:165
client.ts:545 WebSocket connection to 'ws://localhost:4000/graphql' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
SubscriptionClient.connect @ client.ts:545
:4000/graphql:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
apollo-client.js:53 networkError TypeError: Failed to fetch
App.js:119 Uncaught TypeError: Cannot read property 'getAuthUser' of undefined
    at App (App.js:119)
    at renderWithHooks (react-dom.development.js:14803)
    at updateFunctionComponent (react-dom.development.js:17034)
    at beginWork (react-dom.development.js:18610)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22157)
    at workLoopSync (react-dom.development.js:22130)
    at performSyncWorkOnRoot (react-dom.development.js:21756)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at scheduleUpdateOnFiber (react-dom.development.js:21199)
    at dispatchAction (react-dom.development.js:15660)
index.js:1 The above error occurred in the <App> component:
    in App (at src/index.js:32)
    in StoreProvider (at src/index.js:31)
    in ThemeProvider (at src/index.js:30)
    in ApolloProvider (at src/index.js:29)
    in ApolloProvider (at src/index.js:28)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
console.<computed> @ index.js:1
localhost/:1 Uncaught (in promise) TypeError: Cannot read property 'getAuthUser' of undefined
    at App (App.js:119)
    at renderWithHooks (react-dom.development.js:14803)
    at updateFunctionComponent (react-dom.development.js:17034)
    at beginWork (react-dom.development.js:18610)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22157)
    at workLoopSync (react-dom.development.js:22130)
    at performSyncWorkOnRoot (react-dom.development.js:21756)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at scheduleUpdateOnFiber (react-dom.development.js:21199)
    at dispatchAction (react-dom.development.js:15660)
client.ts:545 WebSocket connection to 'ws://localhost:4000/graphql' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by NickNck** [comment]
This errors show up before the welcome page even loads
