### ISSUE TITLE
Program works locally only

### ISSUE THREAD

**Issue by NickNck** [DimiMikadze/orca#56]
Hi I am facing another issue. The app now works locallywith no problem using the address http://localhost:3000 but when i tryto access it on another device using the server address http://192.168.0.102:3000 i get the folowing error:

×
TypeError: Cannot read property 'getAuthUser' of undefined
App
C:/Users/yanic/Downloads/New folder/my-network/frontend/src/components/App/App.js:119
  116 |      <GlobalStyle />
  117 | 
  118 |      <ScrollToTop>
> 119 |        <Switch>
      | ^  120 |          {data.getAuthUser ? (
  121 |            <Route
  122 |              exact
View compiled
renderWithHooks
C:/Users/yanic/Downloads/New folder/my-network/frontend/node_modules/react-dom/cjs/react-dom.development.js:14797
  14794 |     ReactCurrentDispatcher.current = HooksDispatcherOnMountInDEV;
  14795 |   }
  14796 | }
> 14797 | var children = Component(props, secondArg); // Check if there was a render phase update
        | ^  14798 | 
  14799 | if (workInProgress.expirationTime === renderExpirationTime) {
  14800 |   // Keep rendering in a loop for as long as render phase updates continue to
View compiled
updateFunctionComponent
C:/Users/yanic/Downloads/New folder/my-network/frontend/node_modules/react-dom/cjs/react-dom.development.js:16976
  16973 | {
  16974 |   ReactCurrentOwner$1.current = workInProgress;
  16975 |   setIsRendering(true);
> 16976 |   nextChildren = renderWithHooks(current, workInProgress, Component, nextProps, context, renderExpirationTime);
        | ^  16977 | 
  16978 |   if (workInProgress.mode & StrictMode) {
  16979 |     // Only double-render components with Hooks
View compiled
beginWork
C:/Users/yanic/Downloads/New folder/my-network/frontend/node_modules/react-dom/cjs/react-dom.development.js:18503
  18500 |     var _Component = workInProgress.type;
  18501 |     var unresolvedProps = workInProgress.pendingProps;
  18502 |     var resolvedProps = workInProgress.elementType === _Component ? unresolvedProps : resolveDefaultProps(_Component, unresolvedProps);
> 18503 |     return updateFunctionComponent(current, workInProgress, _Component, resolvedProps, renderExpirationTime);
        | ^  18504 |   }
  18505 | 
  18506 | case ClassComponent:
View compiled
HTMLUnknownElement.callCallback
C:/Users/yanic/Downloads/New folder/my-network/frontend/node_modules/react-dom/cjs/react-dom.development.js:189
  186 |     window.event = windowEvent;
  187 |   }
  188 | 
> 189 |   func.apply(context, funcArgs);
      | ^  190 |   didError = false;
  191 | } // Create a global error event handler. We use this to capture the value
  192 | // that was thrown. It's possible that this error handler will fire more
View compiled
invokeGuardedCallbackDev
C:/Users/yanic/Downloads/New folder/my-network/frontend/node_modules/react-dom/cjs/react-dom.development.js:238
  235 | // errors, it will trigger our global error handler.
  236 | 
  237 | evt.initEvent(evtType, false, false);
> 238 | fakeNode.dispatchEvent(evt);
      | ^  239 | 
  240 | if (windowEventDescriptor) {
  241 |   Object.defineProperty(window, 'event', windowEventDescriptor);
View compiled
invokeGuardedCallback
C:/Users/yanic/Downloads/New folder/my-network/frontend/node_modules/react-dom/cjs/react-dom.development.js:291
  288 | function invokeGuardedCallback(name, func, context, a, b, c, d, e, f) {
  289 |   hasError = false;
  290 |   caughtError = null;
> 291 |   invokeGuardedCallbackImpl$1.apply(reporter, arguments);
      | ^  292 | }
  293 | /**
  294 |  * Same as invokeGuardedCallback, but instead of returning an error, it stores
View compiled
beginWork$1
C:/Users/yanic/Downloads/New folder/my-network/frontend/node_modules/react-dom/cjs/react-dom.development.js:23055
  23052 | } // Run beginWork again.
  23053 | 
  23054 | 
> 23055 | invokeGuardedCallback(null, beginWork, null, current, unitOfWork, expirationTime);
        | ^  23056 | 
  23057 | if (hasCaughtError()) {
  23058 |   var replayError = clearCaughtError(); // `invokeGuardedCallback` sometimes sets an expando `_suppressLogging`.
View compiled
performUnitOfWork
C:/Users/yanic/Downloads/New folder/my-network/frontend/node_modules/react-dom/cjs/react-dom.development.js:22022
  22019 |   next = beginWork$1(current, unitOfWork, renderExpirationTime$1);
  22020 |   stopProfilerTimerIfRunningAndRecordDelta(unitOfWork, true);
  22021 | } else {
> 22022 |   next = beginWork$1(current, unitOfWork, renderExpirationTime$1);
        | ^  22023 | }
  22024 | 
  22025 | resetCurrentFiber();
View compiled
workLoopSync
C:/Users/yanic/Downloads/New folder/my-network/frontend/node_modules/react-dom/cjs/react-dom.development.js:21995
  21992 | function workLoopSync() {
  21993 |   // Already timed out, so perform work without checking if we need to yield.
  21994 |   while (workInProgress !== null) {
> 21995 |     workInProgress = performUnitOfWork(workInProgress);
        | ^  21996 |   }
  21997 | }
  21998 | /** @noinline */
View compiled
performSyncWorkOnRoot
C:/Users/yanic/Downloads/New folder/my-network/frontend/node_modules/react-dom/cjs/react-dom.development.js:21613
  21610 | 
  21611 | do {
  21612 |   try {
> 21613 |     workLoopSync();
        | ^  21614 |     break;
  21615 |   } catch (thrownValue) {
  21616 |     handleError(root, thrownValue);
View compiled
(anonymous function)
C:/Users/yanic/Downloads/New folder/my-network/frontend/node_modules/react-dom/cjs/react-dom.development.js:11131
  11128 |     var callback = queue[i];
  11129 | 
  11130 |     do {
> 11131 |       callback = callback(_isSync);
        | ^  11132 |     } while (callback !== null);
  11133 |   }
  11134 | });
View compiled
unstable_runWithPriority
C:/Users/yanic/Downloads/New folder/my-network/frontend/node_modules/scheduler/cjs/scheduler.development.js:659
  656 | currentPriorityLevel = priorityLevel;
  657 | 
  658 | try {
> 659 |   return eventHandler();
      | ^  660 | } finally {
  661 |   currentPriorityLevel = previousPriorityLevel;
  662 | }
View compiled
runWithPriority$1
C:/Users/yanic/Downloads/New folder/my-network/frontend/node_modules/react-dom/cjs/react-dom.development.js:11077
  11074 | 
  11075 | function runWithPriority$1(reactPriorityLevel, fn) {
  11076 |   var priorityLevel = reactPriorityToSchedulerPriority(reactPriorityLevel);
> 11077 |   return Scheduler_runWithPriority(priorityLevel, fn);
        | ^  11078 | }
  11079 | 
  11080 | function scheduleCallback(reactPriorityLevel, callback, options) {
View compiled
flushSyncCallbackQueueImpl
C:/Users/yanic/Downloads/New folder/my-network/frontend/node_modules/react-dom/cjs/react-dom.development.js:11126
  11123 | try {
  11124 |   var _isSync = true;
  11125 |   var queue = syncQueue;
> 11126 |   runWithPriority$1(ImmediatePriority, function () {
        | ^  11127 |     for (; i < queue.length; i++) {
  11128 |       var callback = queue[i];
  11129 | 
View compiled
flushSyncCallbackQueue
C:/Users/yanic/Downloads/New folder/my-network/frontend/node_modules/react-dom/cjs/react-dom.development.js:11114
  11111 |     Scheduler_cancelCallback(node);
  11112 |   }
  11113 | 
> 11114 |   flushSyncCallbackQueueImpl();
        | ^  11115 | }
  11116 | 
  11117 | function flushSyncCallbackQueueImpl() {
View compiled
scheduleUpdateOnFiber
C:/Users/yanic/Downloads/New folder/my-network/frontend/node_modules/react-dom/cjs/react-dom.development.js:21056
  21053 |       // scheduleCallbackForFiber to preserve the ability to schedule a callback
  21054 |       // without immediately flushing it. We only do this for user-initiated
  21055 |       // updates, to preserve historical behavior of legacy mode.
> 21056 |       flushSyncCallbackQueue();
        | ^  21057 |     }
  21058 |   }
  21059 | } else {
View compiled
dispatchAction
C:/Users/yanic/Downloads/New folder/my-network/frontend/node_modules/react-dom/cjs/react-dom.development.js:15634
  15631 |         warnIfNotCurrentlyActingUpdatesInDev(fiber);
  15632 |       }
  15633 |     }
> 15634 |     scheduleWork(fiber, expirationTime);
        | ^  15635 |   }
  15636 | }
  15637 | 
View compiled

**Comment by DimiMikadze** [comment]
@NickNck please stop flooding (opening issues in a every 2 seconds) and respect issue template.
