### ISSUE TITLE
The shared URL for Post is not loading the post instead it is showing "Page Not Found" -- Graphql endpoint URL not generating 

### ISSUE THREAD

**Issue by AmrishKrishnan** [DimiMikadze/orca#60]
**Describe the bug**

The shared URL for Post is not loading the post instead it is showing "Page Not Found"
**Post loads/opens when we click user profile -> Post but doesn't open the same post when accessed using shared Post URL**
I see that graphql URL endpoint is not generated or not used when we open the copied/shared post link.

**System**

Browser version: Chrome (latest Version)
Node.js version: 12.18.2
NPM or Yarn version: - 6.14.5
Operating system: Windows 10 

**Steps to reproduce**

1. Generated the link in the Post's copy Link option
2. Then tried opening the link in a new tab in the same browser / same tab 
3. "Page Not found" -- gives redirect link to my home page
 
**Expected behavior**

Load / Open the post with this request URL ->[https://shielded-lake-75128.herokuapp.com/graphql]( https://shielded-lake-75128.herokuapp.com/graphql )
(This should be the expected URL when we open Post -- This is opening in the Application level) 
This works when we click user profile -> Post but doesn't open the same post when accessed using shared Post URL
 
**Actual behavior**

Loads error page.....with this request URL - [https://amazing-shannon-5a05fb.netlify.app/post/5f1d9e1d76e8590004984515](https://amazing-shannon-5a05fb.netlify.app/post/5f1d9e1d76e8590004984515)
(Found it in inspect Network Tab)

**Reproducible demo**

(Paste the link to an example project and exact instructions to reproduce the issue.)
<img width="960" alt="error screenshot 1" src="https://user-images.githubusercontent.com/33772649/88483742-83621800-cf87-11ea-87ba-223452cc8bd4.PNG">
<img width="958" alt="error screenshot 2" src="https://user-images.githubusercontent.com/33772649/88483744-84934500-cf87-11ea-8c2c-5bf8df9ed65e.PNG">

**Comment by DimiMikadze** [comment]
Hi @Kaappdaw, could you tell me that this issue happens only in production mode or also on the localhost?

If it's only on production mode, I think Netlify isn't configured to handle Single page app routing.

**Comment by AmrishKrishnan** [comment]
Hey @DimiMikadze, the issue got resolved once I moved it from localhost to the production. 

Thank you soo much for your support, I appreciate your concern!
