### ISSUE TITLE
Error during WebSocket handshake

### ISSUE THREAD

**Issue by letoribo** [DimiMikadze/orca#67]
გამარჯობა, გენაცვალე!

thank you for the awesome project!
everything just works, despite the annoying message in console:

![Error during WebSocket handshake](https://user-images.githubusercontent.com/4941581/91091341-1cf01880-e65f-11ea-936b-357cd352c15b.PNG)

how to get rid of that?

https://sad-payne-123151.netlify.app/

**Comment by DimiMikadze** [comment]
Hi @letoribo, thanks. You need to debug Sockets connection and communication with each other, and find out what's causing it. I'm not able to help you without knowing what's the source of problem.

**Comment by letoribo** [comment]
i don't know why the application yet worked,
but after i set REACT_APP_WEBSOCKET_API_URL to wss://cresone.herokuapp.com/graphql
the message has gone.

maybe it would be worth adding this point to frontend-deployment-to-netlify section.
now i'm happy that the console is clean
