### ISSUE TITLE
App only works locally, it does not work externally

### ISSUE THREAD

**Issue by thecaffeinatedengineer** [DimiMikadze/orca#68]
**Describe the bug**
The frontend only works on localhost, when I try to access it externally it returns an error. There is a similar issue that was raised here https://github.com/DimiMikadze/create-social-network/issues/56

**System**

Browser version: Google Chrome Version 84.0.4147.135 (Official Build) (64-bit)
Node.js version: v13.9.0
NPM version: 6.14.4
Operating system: macOS Catalina 10.15.5

**Steps to reproduce**

1. git clone git@github.com:DimiMikadze/create-social-network.git social-network
2. cd social-network && npm start
3. Access app on http://localhost:3000/ confirm it works.
4. Access app on http://192.168.1.253:3000/, confirm it doesn't work

**Expected behavior**

Expected the external link to render the home page like localhost

<img width="1680" alt="Screenshot 2020-08-31 at 20 39 48" src="https://user-images.githubusercontent.com/14309350/91759793-2979f100-ebca-11ea-9315-7f050b970600.png">

**Actual behavior**
An error is displayed.

<img width="1680" alt="Screenshot 2020-08-31 at 20 38 17" src="https://user-images.githubusercontent.com/14309350/91759736-10714000-ebca-11ea-833b-2453f0004f8d.png">

**Reproducible demo**

1. git clone git@github.com:ianchikwature/social-network.git

2. cd social-network && npm start

3. access link at http://192.168.1.253:3000/

**Comment by DimiMikadze** [comment]
@ianchikwature Hi, the program is telling you that `data` is undefined. Now you need to debug it, find out what's the problem, and resolve it.

It could be caused by many things. Maybe you forgot to add environment variables, and the front-end isn't able to connect with the API. Maybe API isn't able to connect to the Database...
