### ISSUE TITLE
Authenticated users can mutate entities on behalf of other users.

### ISSUE THREAD

**Issue by TomKochievi** [DimiMikadze/orca#73]
**Describe the bug**

Authenticated users can mutate entities on behalf of other users. Initially reported at #65.
To fix it, we need to check if the authenticated User's ID on the server matches the User's ID that is sending the request.

**System**

Browser version: Version 85.0.4183.102 (Official Build) (64-bit)
Node.js version: v14.10.0
NPM or Yarn version: yarn 1.22.5
Operating system: Linux. Ubuntu 20.04.1 LTS

**Steps to reproduce**

1. Get the authentication token from the browser.
2. Navigate to GraphQL playground, and send the mutation on behalf of other users.
3. ![Screenshot from 2020-09-16 13-49-33](https://user-images.githubusercontent.com/13495707/93321777-a1c7ef80-f823-11ea-8884-f882e0c0e40a.png)

  The list of the mutations that contains this bug:
  **Posts**
    create, delete
  **Comments**
    create, delete
  **Like**
    create, delete
  **Follow**
    create, delete
  **Notifications**
    create
  **Messages**
    create

**Expected behavior**
It shouldn't mutate an entity and send an error message instead.

**Comment by gonzochic** [comment]
Depending on what you want to allow in the future: 

- Users can't post on behalf of others: Validating the token is enough and there is no need to send and authorID within the request payload. The authorID is simply taken from the token.
- User can post on behalf of others (based on some authorization logic): There you could check if the requesting user (authenticated with a JWT) is allowed to post on behalf of the provided authorID. 

From my perspective (we are working on a forked version), redacting the authorID from the GraphQL Input-Schemas on the Mutation-Queries and simply validating the JWT (obviously extracting the user) is enough.

**Comment by DimiMikadze** [comment]
@gonzochic Hi, thanks for the information. I'll look into it as soon as I'm available 👍.

**Comment by DimiMikadze** [comment]
Hi, I'm closing this issue since we uploaded a new project to this repository. The old one is located here: https://github.com/DimiMikadze/create-social-network-old.
