### ISSUE TITLE
Detect not authorized request

### ISSUE THREAD

**Issue by DimiMikadze** [DimiMikadze/orca#81]
Detect if a User isn't authorized to make a request and automatically sign out from the application.

**Comment by varun2india89** [comment]
Hello, Is this active Repo and I would like to contribute to this lib to make it better,Let me know if it is going to be active project  ?

**Comment by DimiMikadze** [comment]
@varun2india89 Hi, it is. We are transforming it to be a tool for building community platforms. We are in the process of shaping an idea. When we'll finish working on the idea and create a roadmap for the project. We'll be very glad for the contribution.

**Comment by DimiMikadze** [comment]
Hi, I'm closing this issue since we uploaded a new project to this repository. The old one is located here: https://github.com/DimiMikadze/create-social-network-old.
