### ISSUE TITLE
Cloudinary integration failing

### ISSUE THREAD

**Issue by adreszer** [DimiMikadze/orca#85]
**Describe the bug**

After cloning the repository, everything works fine, except of uploading an image (both with own Cloudinary details and those provided as an example). 

**System**

Browser version: Chrome, 85.0.4183.121
Node.js version: v14.4.0
NPM or Yarn version: 6.14.5
Operating system: Windows

**Steps to reproduce**
1. Setup using 
`npx create-social-network my-network`
2. Updated only the database details
3. `yarn start`
4. Either change the Cloudinary details or leave them as they are

**Expected behavior**

Image should be uploaded.

**Actual behavior**

`RangeError: Maximum call stack size exceeded` error is thrown to the console.
<img width="522" alt="Scr" src="https://user-images.githubusercontent.com/12083583/95336126-9743c780-08b0-11eb-9369-96bcf59b68e7.PNG">

**Additional context**

I would like to highlight it happens with both: leaving and changing Cloudinary details in .env file. Am I doing something wrong, perhaps?

**Comment by adreszer** [comment]
Found a solution, not an ideal one, but I managed to make it work with both, your Cloudinary details and my own. 

to all three package.json files add:
`"resolutions": {
		"fs-capacitor": "3.0.0"
	}`
And inside **api** and **frontend** directories install `fs-capacitor` packages.

**Comment by DimiMikadze** [comment]
Hi @adreszer, thanks for reporting the issue. I'll try to fix it soon.
