### ISSUE TITLE
Error "RangeError: Maximum call stack size exceeded". Cannot post pictures in any of the pages.

### ISSUE THREAD

**Issue by nvan23** [DimiMikadze/orca#90]
**Describe the bug**

After the application installation completes and configuring the application (with the mongodb local option), I cannot post the image in any page compared to the previous version.

**System**

Browser version: Chrome 86.0.4240.198
Node.js version: v14.15.1
NPM or Yarn version: 6.14.9
Operating system: Window 10

**Steps to reproduce**

1.  Start the server and client via command "npm start" at root folder
2. Client side: try posting pictures on any page.

**Expected behavior**

I can post normal photos like the previous version I used to.

**Actual behavior**

I can not post normal photos.

**Comment by koin-master** [comment]
I have the same problem
did you find a solution please? : ((

**Comment by DiceRandom** [comment]
solution?

**Comment by alexiskattan** [comment]
bump
