### ISSUE TITLE
UnhandledPromiseRejectionWarning: JsonWebTokenError: jwt must be provided

### ISSUE THREAD

**Issue by Shiba-Kar** [DimiMikadze/orca#92]
**UnhandledPromiseRejectionWarning: JsonWebTokenError: jwt must be provided**

on running
*>npm run start:api*

I am getting 
server ready at http://localhost:4000/graphql
Subscriptions ready at ws://localhost:4000/graphql
DB connected

*as soon as I navigate to any of the links I get the above error !!!.*

`
(node:11896) UnhandledPromiseRejectionWarning: JsonWebTokenError: jwt must be provided
    at Proxy.module.exports (C:\Programming\Node.js\create-social-network\api\node_modules\jsonwebtoken\verify.js:53:17)
    at C:\Programming\Node.js\create-social-network\api\utils\apollo-server.js:17:32
    at new Promise (<anonymous>)
    at checkAuthorization (C:\Programming\Node.js\create-social-network\api\utils\apollo-server.js:16:10)
    at ApolloServer.context (C:\Programming\Node.js\create-social-network\api\utils\apollo-server.js:45:28)
    at ApolloServer.<anonymous> (C:\Programming\Node.js\create-social-network\api\node_modules\apollo-server-core\dist\ApolloServer.js:546:38)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Programming\Node.js\create-social-network\api\node_modules\apollo-server-core\dist\ApolloServer.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:11896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate 
the Node.js process with a non-zero exit code.
`
**System**

Browser version: Chrome Version 87.0.4280.88 (Official Build) (64-bit)
Node.js version: v12.18.2
NPM or Yarn version: v6.14.7
Operating system: win10 latest home

**Steps to reproduce**

1. Navigate to root directory of the project
2. npm run start:api
3. http://localhost:4000/graphql

**Expected behavior**

Should run the server and graphql

**Comment by DimiMikadze** [comment]
@Shiba-Kar the GraphQL playground is protected, you can't access it without passing an authentication token.

https://github.com/DimiMikadze/create-social-network/issues/36#issuecomment-571909941

**Comment by Shiba-Kar** [comment]
Please cound you tell me how can i do 

> @Shiba-Kar the GraphQL playground is protected, you can't access it without passing an authentication token.
> 
> [#36 (comment)](https://github.com/DimiMikadze/create-social-network/issues/36#issuecomment-571909941)

Could you please tell me how it can be done.

**Comment by RandyWuchi** [comment]
> Please cound you tell me how can i do
> 
> > @Shiba-Kar the GraphQL playground is protected, you can't access it without passing an authentication token.
> > [#36 (comment)](https://github.com/DimiMikadze/create-social-network/issues/36#issuecomment-571909941)
> 
> Could you please tell me how it can be done.

Change the checkAuthorization function in utils/apollo-server.... Like this

const checkAuthorization = (token) => {
  try {
    const authUser = jwt.verify(token, process.env.SECRET_KEY);

    return authUser;
  } catch (error) {
    return "";
  }
};

**Comment by Faiyaz-cmd** [comment]
its Not working bro
