### ISSUE TITLE
× Unhandled Rejection (TypeError): Cannot assign to read only property 'newNotifications' of object '#<Object>'

### ISSUE THREAD

**Issue by nvan23** [DimiMikadze/orca#94]
**Describe the bug**

I try to follow someone and the error occurs after I see all my notifications.

`Uncaught (in promise) TypeError: Cannot assign to read only property 'newNotifications' of object '#<Object>'`

![image](https://user-images.githubusercontent.com/44724339/101655568-5749be00-3a74-11eb-9ef7-110d77840409.png)

**System**

Browser version: Chrome 86.0.4240.198
Node.js version: v14.15.1
NPM or Yarn version: 6.14.9
Operating system: Window 10

**Steps to reproduce**

1. Login via account A
2. Post any image
3. Search and follow, send messges to account B
4. Login via account C and give a comment on post of account A
5. Login via account B, find post of account A and go to comments list, go to account C and press follow

**Expected behavior**

Follow account C successfully.

**Actual behavior**

None

**Reproducible demo**

None

**Additional context**

None

**Comment by DimiMikadze** [comment]
Hi @nvan23 were you able to fix this issue on your end?

**Comment by nvan23** [comment]
Hi @DimiMikadze, unfortunately I have not fixed this problem right now but if I fix it I will tell you right away.

**Comment by bharatgpatil** [comment]
Did you solve this issue? @DimiMikadze @nvan23

**Comment by shackhornold** [comment]
Have the same problem. I'm also getting the same when trying to message a user `TypeError: "newConversations" is read-only`

**Comment by SandroMueller** [comment]
Me too

**Comment by undigitals** [comment]
It's because of "strict mode"

```js
const authUser = prev.getAuthUser;
// authUser is readonly
authUser.newNotifications = newNotifications;

// change to this.  This is object spread operator.
const authUser = { ...prev?.getAuthUser, newNotifications };
```

**Comment by undigitals** [comment]
And you will have the same issue on `pages/Messages/MessagesChatHeading.js`

```js
// old code
chatUser.isOnline = data?.isUserOnline?.isOnline;

// change to this
chatUser = {...chatUser, isOnline:data?.isUserOnline?.isOnline}
```

I am checking through all codebase if I find same error, I will keep fixing and posting here.

**Comment by DimiMikadze** [comment]
Hi, I'm closing this issue since we uploaded a new project to this repository. The old one is located here: https://github.com/DimiMikadze/create-social-network-old.
