### ISSUE TITLE
WebSocket connection to 'ws://localhost:4000/graphql' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by fazelukario** [DimiMikadze/orca#97]
Getting error

![image](https://user-images.githubusercontent.com/46999684/102292465-e01d9980-3f4d-11eb-8f27-8d6547fdf3b1.png)

**System**

Browser version: Chrome 87.0.4280.88
Node.js version: v10.23.0
NPM or Yarn version: npm 6.14.9
Operating system: 

**Steps to reproduce**

1.Launch here: http://91.90.17.66:3000/

**Actual behavior**

Getting error:
WebSocket connection to 'ws://localhost:4000/graphql' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Reproducible demo**

http://91.90.17.66:3000/

**Comment by DimiMikadze** [comment]
You need to use `http://localhost:3000/` or update the corresponding environment variable with the new hostname.

**Comment by fazelukario** [comment]
So, in which file i can change this params?
